/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    status: JobStatusEnum;
    /**
     * Error message if the job failed
     * @type {string}
     * @memberof Job
     */
    error?: string;
}


/**
 * @export
 */
export const JobStatusEnum = {
    Pending: 'pending',
    Scheduled: 'scheduled',
    Available: 'available',
    Running: 'running',
    Completed: 'completed',
    Cancelled: 'cancelled',
    Discarded: 'discarded',
    Retryable: 'retryable'
} as const;
export type JobStatusEnum = typeof JobStatusEnum[keyof typeof JobStatusEnum];


/**
 * Check if a given object implements the Job interface.
 */
export function instanceOfJob(value: object): value is Job {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function JobFromJSON(json: any): Job {
    return JobFromJSONTyped(json, false);
}

export function JobFromJSONTyped(json: any, ignoreDiscriminator: boolean): Job {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function JobToJSON(value?: Job | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'status': value['status'],
        'error': value['error'],
    };
}

