name: Build and push images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: quay.io
      # Set tag to the last commit sha on main branch, otherwise tag will be the branch name
      REGISTRY_TAG: ${{ (github.head_ref||github.ref_name)=='main' && github.sha || (github.head_ref||github.ref_name) }}

      REGISTRY_ORG: kubev2v
    steps:
      - name: Checkout forklift
        uses: actions/checkout@v4

      - name: Login to quay.io with bot account
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push images to quay.io
        run: |
          cd ${GITHUB_WORKSPACE}
          podman build . -f Containerfile -t $REGISTRY/kubev2v/migration-planner-ui
          podman build . -f Containerfile --label "quay.expires-after=10d" -t $REGISTRY/kubev2v/migration-planner-ui:$REGISTRY_TAG
          
          podman push $REGISTRY/kubev2v/migration-planner-ui
          podman push $REGISTRY/kubev2v/migration-planner-ui:$REGISTRY_TAG       
  
  publish_npm:
    runs-on: ubuntu-latest
    needs: build_push
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.5.0 --activate

      - run: yarn install --immutable
      - run: yarn all:lint
      - run: yarn all:build

      - name: Increment beta version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          current_version=$(node -p "require('./package.json').version")
          IFS='-' read -ra VERSION_PARTS <<< "$current_version"
          IFS='.' read -ra NUMBER_PARTS <<< "${VERSION_PARTS[0]}"
          new_patch=$((NUMBER_PARTS[2] + 1))
          new_version="${NUMBER_PARTS[0]}.${NUMBER_PARTS[1]}.$new_patch-${VERSION_PARTS[1]}"
          npm version $new_version -m "Bump version to %s"
          git push
          git push --tags

      - name: Configure npm credentials
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
          cat .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

