name: Notify planner repo
on:
  workflow_run:
    workflows: [ "migration-planner-agent-ui-on-push" ]   # Notify only after the image was builded
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.MIGRATION_PLANNER_SYNC_APP_ID }}
          private-key: ${{ secrets.MIGRATION_PLANNER_SYNC_APP_PRIVATE_KEY }}
          owner: kubev2v
          repositories: migration-planner

      - name: Send repository_dispatch
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/kubev2v/migration-planner/dispatches \
            -d '{
              "event_type": "remote_repo_updated",
              "client_payload": {
                "sha": "${{ github.event.workflow_run.head_sha }}",
                "repo": "${{ github.event.workflow_run.head_repository.full_name }}"e }}"
              }
            }'
